#!/bin/bash

pip install numpy
pip install pandas
pip install fuzzywuzzy
pip3 install matplotlib
pip3 install --upgrade google-cloud-storage
pip install --upgrade google-cloud-storage
pip install google-cloud-core
pip install google-api-core
pip install google-api-core
pip install google-auth
pip install google-cloud-bigquery
pip install google-cloud-storage
pip install google-cloud-core
pip install googleapis-common-protos

pip install .
jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode

#EOF
